name: Samtal P책g책r
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3650728836655617
title: Samtal P책g책r
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00757a'
    - '#f3e5d8'
    - '#9bb2af'
    - '#2b8385'
    - '#5b9f9d'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
