name: Samtal P책g책r
favicon: null
layout_spectrum: 0.27830731798894703
typography_spectrum: 0.3650728836655617
title: Samtal P책g책r
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00757a'
    - '#f3e5d8'
    - '#9bb2af'
    - '#2b8385'
    - '#5b9f9d'
  brandStrength: 0.625
  lightness: 0.28434810345061123
  saturation: 0.7593997195363045
  rhythmicContrast: 0.20741293532773852
purpose: []
