name: Samtal Pågår
favicon: null
layout_spectrum: 0.27830731798894703
typography_spectrum: 0.3650728836655617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6185792181640863
  lightness: 0.28434810345061123
  saturation: 0.7593997195363045
  rhythmicContrast: 0.20741293532773852
purpose: []
